"""PROBLEM 2:
Each new term in the Fibonacci sequence is generated by adding the previous two
 terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

"""

n0 = 0
n1 = 1
cond = True
fib = []
while cond == True:
    n = n0 + n1
    if n > 4000000:
        cond = False
        break
    else:
        pass
    if n % 2 ==0 :
        fib.append(n)
    else:
        pass
    n0 = n1
    n1 = n

total = 0
for num in fib:
    total = total + num

print total
